### ISSUE TITLE
string 类型的value 在windows 窗口下需要优化

### ISSUE THREAD

**Issue by ariallyp** [cc20110101/RedisView#16]
string type value 需要优化，另外 value上面的 key 长度太短，需
![1](https://user-images.githubusercontent.com/33079377/72318379-12d46780-36d7-11ea-9c27-cf3ab0724844.png)
![2](https://user-images.githubusercontent.com/33079377/72318386-1536c180-36d7-11ea-8c2d-284d8a6062e2.png)

要长点就好。

**Comment by cc20110101** [comment]
1.7.1新增了查看键值对话框，可以显示全
