### ISSUE TITLE
希望能够提供 Mac 版本

### ISSUE THREAD

**Issue by XuJinNet** [cc20110101/RedisView#2]
很好的软件 👍
我是刚开始使用 Redis，正在寻找一个好用的桌面客户端程序，正好看到这个项目。
强烈希望作者能够提供 Mac 版本！！！！

**Comment by XuJinNet** [comment]
不好意思，刚在下载页面看到已经提供了 Mac 版本 👍

**Comment by cc20110101** [comment]
有mac、linux、win三平台，主要win平台开发。mac和linux虚拟机编译的，也没有设置软件图标，有max可以自己修改源码设置图标

**Comment by XuJinNet** [comment]
已经下载了，持续关注。
