### ISSUE TITLE
批量操作无法选择Db?

### ISSUE THREAD

**Issue by imvvip** [cc20110101/RedisView#21]
我按https://blog.csdn.net/cc20110101/article/details/87301562上说明对测试环境的redis进行了批量删除操作，结果发现是把所有db下的数据都删除了。是操作方式不对吗？谢谢

**Comment by cc20110101** [comment]
集群模式只使用一个db; 单例模式调用scan全扫，没法设置db

**Comment by cc20110101** [comment]
选择db删除只能通过左边键列表选择键删除，批量操作里面不行

**Comment by imvvip** [comment]
意思是，不能flush db的操作咯？

**Comment by cc20110101** [comment]
批量删除是删除特定键模式的KEY，没有根据DB进行全部删除；你的场景如果是想删除某个DB的全部数据，可以从工具命令行界面执行select dbinex;   flush db试试

**Comment by imvvip** [comment]
命令：
select db3; flush db
结果：
ERR invalid DB index
ERR unknown command `flush`, with args beginning with: `db`,

**Comment by cc20110101** [comment]
集群模式：只有0号数据库可用，直接执行批量删除即可
单例模式：select 3; flush db

**Comment by imvvip** [comment]
谢谢。
单例模式，改成你的方法，结果是前一个命令正确，但后一个命名还是错误。我的redis版本是5.0.8，是不是版本原因？linux下的docker模式安装的

**Comment by imvvip** [comment]
select 3; flushdb
这样就ok了。
谢谢回复
