### ISSUE TITLE
linux v1.6使用localhost：6379+密码无法连接

### ISSUE THREAD

**Issue by defuse1999** [cc20110101/RedisView#3]
#1 使用fastoredis测试可以连接成功，127.0.0.1可以连接
#2 没有保存连接记录
#3 无法输入中文

**Comment by cc20110101** [comment]
1、localhost这种方式没支持，填写ip
2、连接记录配置后保存了，你说的是按连接记录排序连接配置吗
3、中文不能输入是说的那里呀

**Comment by defuse1999** [comment]
首先，谢谢作者的回复，
我使用的linuxmint 19 + xfce桌面，使用RedisView启动就可以保存连接，appimage不能保存（可以理解）
输入法 fitcx --> 搜狗，输入中文value时不能正常输入

**Comment by cc20110101** [comment]
mac和linux程序图标都没设置，程序也是从虚拟机编译的；
linux中文输入没测试过；

**Comment by defuse1999** [comment]
可能是我发行版的问题
