### ISSUE TITLE
用户操作与编码问题

### ISSUE THREAD

**Issue by rookiechw** [cc20110101/RedisView#4]
1.  希望可以提供一个按钮回到选择redis连接的入口
2. 中文存在乱码情况,是否可以考虑支持自定义编码？
`{"orgName":"378搴楅暱"}`

**Comment by cc20110101** [comment]
1、当时做时候，我们生产环境数据量达到1000万key，会占用大内存，当时就做成只允许一个连接存在了；
你说的这个返回连接入口是可以增加的
2、源码新增选择编码，还未编译；但是存在非GB18030编码使用命令行操作时，键为中文会乱码

**Comment by cc20110101** [comment]
版本更新了，可以下载试下

**Comment by rookiechw** [comment]
感谢！

**Comment by cc20110101** [comment]
等下重下载下，重新在上传

**Comment by gzatxm** [comment]
中文还是有乱码

**Comment by rookiechw** [comment]
> 中文还是有乱码

设置了编码格式没？

**Comment by cc20110101** [comment]
1.6.2版本还有乱码？ RedisView工具和Redis原带Redis-cli命令都执行下，看下是否乱码，什么编码存储的就用什么编码显示试下呢
