### ISSUE TITLE
Error: parser resp type failed

### ISSUE THREAD

**Issue by LuomingXu** [cc20110101/RedisView#5]
查看数据的时候出现错误
=

![image](https://user-images.githubusercontent.com/24503603/54331048-2cd69100-4653-11e9-9085-510fe2417384.png)
## 我在RDBTools里面查看的时候没有问题
![image](https://user-images.githubusercontent.com/24503603/54331134-7c1cc180-4653-11e9-8ee1-617c982ce223.png)

## 使用的是v1.6.0

**Comment by cc20110101** [comment]
方便把哈希的键、字段、值发下么，redis-cli客户端命令获取的，我测试下

**Comment by LuomingXu** [comment]
@cc20110101 
#### Hash: 
- Key: Token:Valid:TokenIsKey
- Field: H+VtoeBpcRccerVGI95xnqIv+emq+zfLxxfV+G13DcKcORJbPvKvBwWZSHlenb/vAl7IDwob3/e73bSRGrmba9T8VDDX9YY1dWHjYGSSyaDWN1SqyiPvOS4b1ECy9Z97AFj80DFeiibj32jQSusG5teaw47M1ztOs0k0RfM2qDT1UjgtGF+jb8NslMRpkuCd8Z4XU099w15vKxGa+CL5Gk0GzEy+ZttpcN3A9syDRflPEZaz8thXFr4p0Ap9DByICq++eGi342MsrtTDqvM0DJgxJ0Ne44s8K96gb4Q/mtpXi8+1GeyrCMp3EmE3Tp5+iUau85aEcnpHCyrlDd28Lbb8A6/jRdxgtb/4TLNddAfvhP0w1LVI3obPzobm
- Value: 0

**Comment by cc20110101** [comment]
我刚试了可以。

![a](https://user-images.githubusercontent.com/12064991/54354701-4814c100-4692-11e9-8802-7bf004ae27c0.jpg)
![b](https://user-images.githubusercontent.com/12064991/54354720-506cfc00-4692-11e9-96dd-2ebb01f0a750.jpg)

**Comment by cc20110101** [comment]
你那里只是这个键报错么，其他的key有报错么

**Comment by LuomingXu** [comment]
@cc20110101 
你是我用的这个版本吗? 
我用的是你release的这个版本
如果你也是这个版本, 且没问题的话, 那有可能就是我的问题了, 
或者你现在的这个版本已经没了这个问题...
那你就改一下那个拼写错误就算了...我来看看是我的什么问题...

**Comment by cc20110101** [comment]
1、拼写错误的已经修改提交到github里面了；等后面改完成其他问题在编译个版本；
2、报错resp type解析失败，你的redis是那个版本的，我的5.0.3测试的，正常服务端返回的resp格式消息应该一样的才对
3、源码Qt写的，下载开发环境，项目打开就可以编译，熟悉的话也可以自己调试下。 工具下载地址：https://download.qt.io/official_releases/qt/5.12/5.12.2/

**Comment by LuomingXu** [comment]
@cc20110101 
可以, 谢谢.
