### ISSUE TITLE
希望添加端口配置

### ISSUE THREAD

**Issue by zipg** [cc20110101/RedisView#8]
希望添加端口配置，还有 如何区分集群与非集群的节点呢？
![image](https://user-images.githubusercontent.com/4047349/59494597-16450d80-8ec0-11e9-84e4-a2129def853d.png)

**Comment by cc20110101** [comment]
端口配置是什么意思，不管是单例、复制机、还是集群模式，你只需要在address填写一个ip:port即可了。
比如，集群地址端口是192.168.220.129:8000,192.168.220.130:9000,192.168.220.131:8000,192.168.220.132:9000,192.168.220.133:8000,192.168.220.134:9000；那么address里面填写任意一个IP端口，如192.168.220.131:8000；当然也可以填写多个，如192.168.220.131:8000,192.168.220.132:9000；
Name随便写，Password是密码，如果没密码可以不填写

**Comment by zipg** [comment]
> 端口配置是什么意思，不管是单例、复制机、还是集群模式，你只需要在address填写一个ip:port即可了。
> 比如，集群地址端口是192.168.220.129:8000,192.168.220.130:9000,192.168.220.131:8000,192.168.220.132:9000,192.168.220.133:8000,192.168.220.134:9000；那么address里面填写任意一个IP端口，如192.168.220.131:8000；当然也可以填写多个，如192.168.220.131:8000,192.168.220.132:9000；
> Name随便写，Password是密码，如果没密码可以不填写

不好意思，没注意到Address输入框里的提示，issue关掉吧。
软件很好用，希望作者有空能继续完善。
